
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "demo-go-server.fullname" . }}
  labels:
    {{- with .Values.backstageLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "demo-go-server.fullname" . }}

